### ISSUE TITLE
1926年12月24日の元号の扱い

### ISSUE THREAD

**Issue by hitomine** [nagataaaas/Japanera#1]
初めまして。
EraDateの使用法について質問です。

```python
print(EraDate(1926, 12, 23).strftime("%-E%-o年%m月%d日"))
print(EraDate(1926, 12, 24).strftime("%-E%-o年%m月%d日"))
print(EraDate(1926, 12, 25).strftime("%-E%-o年%m月%d日"))
```

上記のコードを実行すると出力結果が以下のようになります。

```
大正15年12月23日
西暦26年12月24日
昭和01年12月25日
```

これはバグでしょうか？それとも仕様でしょうか？
また、1926年12月24日を「大正」として扱うにはどのようにすればよいでしょうか。
アプリケーション側で対処するしかないのでしょうか。

よろしくお願いします。

**Comment by hitomine** [comment]
2019/11/27現在 pip install で取得できるバージョンを使用しています
Pythonのバージョンは 3.8です

**Comment by nagataaaas** [comment]
すみません、日付データが1日ズレていました…
修正したので新バージョンを利用ください。
