### ISSUE TITLE
Japanera 2.1.1 vs kanjize 1.5.0

### ISSUE THREAD

**Issue by kazuya-yamada-gq** [nagataaaas/Japanera#10]
いつもお世話になっております。
Japanera 2.1.1のrequirement.txtにはkanjize==1.5.0とあるのですが、pip install -U Japaneraではkanjize 1.4.0がインストールされ、あらためてpip install -U kanjizeすると、以下のエラーが表示されます。
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
japanera 2.1.1 requires kanjize==1.4.0, but you have kanjize 1.5.0 which is incompatible.

**Comment by nagataaaas** [comment]
こちら対応遅くなりすみません...
@uchiuzo-sansan 様がPRを作ってくださいました 🙇

**Comment by kazuya-yamada-gq** [comment]
ご対応ありがとうございます。
このPRがPyPiに反映されるのはどういったタイミングになりますでしょうか？
現状、Japaneraが未インストールの仮想環境にpip install Japaneraを実行するとkanjize 1.5.0ではなくkanjize 1.4.0がインストールされるようです。

**Comment by nagataaaas** [comment]
失礼しました...
githubでmergeして満足していました...
pypiにアップロードいたしました！

**Comment by kazuya-yamada-gq** [comment]
早速のご対応ありがとうございます。Japaneraが未インストールの仮想環境にpip install Japaneraを実行すると、Japanera 2.1.2とkanjize 1.5.0がインストールされるようになりました。
