### ISSUE TITLE
Unable to parse single-digit months or dates

### ISSUE THREAD

**Issue by fritz-c** [nagataaaas/Japanera#3]
Thank you for making such a helpful library. It does everything I need, but it seems to have a small bug.

When I run the following code, it fails to parse the date.

```py
from japanera import Japanera
janera = Japanera()

janera.strptime('昭和27年3月14日','%-E%-O年%m月%d日')
# => []
```

The issue appears to be with this line of code:
https://github.com/delta114514/Japanera/blob/042996abc07d46c8790ff98f74a38702cf4ae3b3/japanera/japanera.py#L970

I think the problem is that `%m` and `%d` are ambiguous during parsing - they will parse either single-digit values or zero-padded values, but when formatting, they will always output the zero-padded form. So your check probably fails because
```
"昭和27年3月14日" !=
"昭和27年03月14日"
```

After commenting out the line I mentioned, it parses the date properly.

**Comment by nagataaaas** [comment]
Thank you for Creating an issue and report a bug.

I Just updated Japanera and fixed this bug by deleting the line you mentioned.

**Comment by fritz-c** [comment]
Thank you!
