### ISSUE TITLE
Support for single digit year

### ISSUE THREAD

**Issue by sobuen** [nagataaaas/Japanera#4]
すばらしいライブラリありがとうございます！重宝させていただいています。
一点、機能の要望ですが、和暦の 1 桁年にご対応いただけませんでしょうか。

現状、`Japanera().strptime('令和2年9月1日', "%-E%-O年%m月%d日")` とすると `ValueError` の例外が飛ぶかと思います。
おそらく strptime 本家の方で `'y': r"(?P<y>\d\d)"` となっているためと考えられます。

<https://github.com/nagataaaas/Japanera/blob/a038d228fa47d5f7690c8a2ee4451719fa82aa51/japanera/japanera.py#L41> の辺りで
```python
format_regex = _TimeRE_cache.compile(format)
format_regex = re.compile(format_regex.pattern.replace('(?P<y>\\d\\d)', '(?P<y>\\d|\\d\\d)'), re.IGNORECASE)
```
等とすれば 1 桁年にも対応できるかと思います。（が、力技できれいでない気がします。あとここで対応するのが適切か不明です。）
一度ご検討いただけると幸いです。

**Comment by nagataaaas** [comment]
機能追加のリクエストありがとうございます。

パース時のみ、1桁の数字も許容するように書き直しました。
sobuenさんのおっしゃるよう、_TimeREの方を編集することで解決しています。

繰り返しになりますが、ありがとうございました。

**Comment by sobuen** [comment]
ご対応ありがとうございます！
